dist: trusty
sudo: false
language: java
jdk:
- oraclejdk11
install: true

addons:
  sonarcloud:
    organization: "isa"
    token:
      secure: "hMg04l3xousHI3LffcgJDzwne9c34leTLsbAUz9VtuYt3p82cv1ghoyZn3Lp+DC6ixbwfWxtxKYXlseoYF3xxpoBMcA4bF9cDn8/9W0H+StJUpvQdODMMT22eVOptFCYYJt5vM9838sEzQr/kSO4iidPcb9liAP+g5Kp4fOvxgyEjBGHiYzf2IhSLy0Xrr2JsJvow/9TPoE68yZ3IUcQHCDCAifrjPWaYqQhJIAlkOvB598CNWbsDRHds7JZt0WMBusbJyGDEhw63LmZkDjUpiuVBf9grBDXBSMY0BCOJ3qrFIwOAysN0ns/giseivk7X0idZXawkfr+qLkKV7cze8vyrlrJzvUSHWGz0uG89SKLOswAIyrjd5K+yf4tX2XaESdNqxdBopumv8t+GHQpNTw3tNQOKIaLO/AF/ortInl1G90xh09OLvAZMyY5JmGYkM3StUoXWp9Lnyg5nFecHYYJ2vh8XTCnPyPcNEJyKJ8s05MMs/78vUcE9WEz38eqWbU5LjGQz40sMHy9xh6/e+vhKodZyqgwK3zqxFAb5LMal1IiIrsXmk391YomLVrUzzWHWQFE5MriVdv31fbWwL1f16Q+nXADVL94EtjB0lrcHMwDBfEyjwLk5jtCOmLyzavjXWd5ZjxN9/vQGwNYWUOQllb9WLKpOz9a1kpJnM8="

branches:
  only: develop

matrix:
  include:
    - language: java
      jdk:
      - oraclejdk11
      before_script:
        - cd ./pharmacy/
      script:
        - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=stiven98_ISA
      cache:
      directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache' 
      before_script:
        - cd ./pharmacy/

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./pharmacy-frontend/
      script:
        - npm run build
        - sonar-scanner -Dsonar.projectKey=stiven98_ISA