dist: trusty
sudo: required

branches:
  only: develop

matrix:
  include:
    - language: java
      jdk:
      - oraclejdk11
      - openjdk11
      script:
        - mvn clean install
      before_script:
        - cd ./pharmacy/

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./pharmacy-frontend/
      script:
        - npm run build